spring.application.name=policy-billing-engine

spring.datasource.url=jdbc:postgresql://localhost:5432/policy_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.info.env.enabled=true
management.metrics.tags.application=${spring.application.name}

info.app.name=Policy Billing Engine
info.app.version=1.1.0-SNAPSHOT
info.app.description=Recurring mobile insurance policy billing engine
info.app.architecture=Hexagonal Architecture
